### PR TITLE
Apply 'weak' to delegate property to avoid from reference cycle.

### PR DESCRIPTION
**Pull request by loongman**
@Finalet Great if you can take a look and merge it to main branch if it works to you.

### CODE REVIEW

**Comment by Finalet** [comment]
Thank you for the input. Although I understand the logic, this does not seem to do anything. The demo app still retains all previously presented emoji pickers in memory.

image

**Comment by loongman** [comment]
Good catch. @Finalet 

It turns out there are some other reference cycle issues. Have updated the fix now.

Have also double checked the memory usage after select different emojis multiple times.
Screenshot 2023-05-31 at 10 55 12

**Comment by Finalet** [comment]
@loongman I see the changes you've made and agree. But it's strange, because memory is still not being released on my end. I checked out your branch and you can see the results below. Perhaps there are some reference cycles that were missed? How did you test on your attached screenshot? 

https://github.com/Finalet/Elegant-Emoji-Picker/assets/10033440/b7137285-8815-4d3a-b655-2d361364a46e

**Comment by loongman** [comment]
@Finalet Any chance still the formal version were in-using while you do the verification on your side due to cache even after you replaced the package url?

Could you try remove the package at first, then, clean build folder by selecting "Product" > "Clean Build Folder" in Xcode, and remove the local cache at `~/Library/Caches/org.swift.swiftpm/repositories`, then, add my fork's package and try again?

In addition, from your video record, there is a `Politeness` section on the picker, which indicates there are some other local changes(?) on the Demo project?

On my side, the only checkout files are `Demo.xcodeproj/project.pbxproj` and `Demo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved` which related to the package replacement(my fork) for debug purpose.

Below you can see the test on my side, the original issue is gone.
Though, there seems to be still another issue exist, at beginning, the memory usage is around 8.2M, after open the picker first time, it increased to 24.1M. Open and close the picker multiple times, the memory is stay around 27M. Ideally, it should go back down to its initial value, aka, 8.2M. However, i'd suggest we split this part out from current PR, and handle it with another PR after dive more deeper. Does that make sense?

https://github.com/Finalet/Elegant-Emoji-Picker/assets/2167359/1945411e-70cf-4c5e-9215-3c1de387f1fa

**Comment by Finalet** [comment]
I have tried on a clean demo project, and with cleaning the build folder, but neither helped. It is also strange that my simulator consumes around 20mb just after launching the app, compared to your 8.2mb. Might be issues on my end as I am not running the latest version of xcode. 

Either way, I will merge this PR. The changes you've made are correct and reflect how this code should have been written from the start.

Thank you for your help, @loongman!

**Pull request merged**
